// ─────────────────────────────────────────────────────────────────────────────
// CONFIG  — bio, links, education, skills, pinned slugs. Edit here.
// ─────────────────────────────────────────────────────────────────────────────
const config = {
  user: {
    name: 'Punnatorn Boonkrajang',
    surname: 'Boonkrajang',
    given: 'Punnatorn',
    nickname: 'Pun',
    handle: 'Punkharb',
    roleSought: 'Software Engineering Intern',
    season: 'Summer 2026',
    bio: "I'm a second-year Computer Science student at KMUTT in Bangkok, working at the edge of mobile and full-stack. I like small, type-safe tools, careful APIs, and shipping things that other students actually use.",
    aboutLong: "I started writing code at 14, building Flutter apps for my school's clubs. Since then I've drifted across stacks — Spring on the backend, React Native on mobile, Go for self-hosted side projects, and a PyTorch detour last semester for a Thai-handwriting classifier. I care most about the seam between systems: making mobile clients that don't lie about state, and backends that don't make mobile clients lie. Outside of code I read essays, run badly, and brew filter coffee.",
    now: [
      { label: 'Building',   value: 'a KMUTT shuttle-bus tracker that ~600 students rely on' },
      { label: 'Learning',   value: 'Rust — slowly, through Crafting Interpreters' },
      { label: 'Reading',    value: '“Designing Data-Intensive Applications”' },
      { label: 'Listening',  value: 'lo-fi while I shower-thought my way through bugs' },
    ],
    spokenLanguages: [
      { name: 'Thai',    level: 'Native' },
      { name: 'English', level: 'Professional · C1' },
      { name: 'Japanese',level: 'Conversational · N4' },
    ],
    activities: [
      { year: '2024', title: 'National Olympiad in Informatics — Thailand', detail: 'Participant · top regional round' },
      { year: '2025', title: 'KMUTT Mini-Hackathon',                       detail: 'Built shuttle-bus tracker · 1st place, mobile track' },
      { year: '2025', title: 'OSS contributions',                           detail: 'Patches to flutter-riverpod and a Spring Boot HTMX starter' },
      { year: '2025', title: 'KMUTT CS Society',                            detail: 'Co-organiser of weekly study sessions for first-year CS' },
    ],
    email: 'punnatorn.bo@mail.kmutt.ac.th',
    github: 'github.com/Punkharb',
    githubUrl: 'https://github.com/Punkharb',
    linkedin: 'linkedin.com/in/punnatorn',
    location: 'Bangkok, Thailand',
    cvFile: 'punnatorn-boonkrajang-cv.pdf',
    avatarInitials: 'PB',
  },
  pinnedRepos: [
    'flutter-pomodoro', 'spring-tasks', 'pytorch-thai-handwriting',
    'flutter-bus-tracker', 'react-native-receipts', 'go-rss',
  ],
  education: [
    {
      school: 'King Mongkut\u2019s University of Technology Thonburi (KMUTT)',
      degree: 'B.Eng. Computer Science · 2nd year',
      years: '2024 — 2028',
      detail: 'GPAX 3.78 / 4.00 · Coursework: Data Structures, OOP, Database Systems, Software Engineering, Discrete Math',
    },
  ],
  skills: {
    'Languages':   ['TypeScript', 'Dart', 'Python', 'Java', 'Go', 'SQL'],
    'Mobile':      ['Flutter', 'React Native', 'Material 3'],
    'Frontend':    ['React', 'Next.js', 'Tailwind', 'Vite'],
    'Backend':     ['Spring Boot', 'Node.js', 'Express', 'PostgreSQL', 'Redis'],
    'ML / Data':   ['PyTorch', 'NumPy', 'pandas', 'scikit-learn'],
    'Tooling':     ['Git', 'Docker', 'Linux', 'GitHub Actions'],
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// REPO CACHE — AI-generated summaries + metadata.
// In a real deploy this would be regenerated by a Cron + the README + an LLM.
// ─────────────────────────────────────────────────────────────────────────────
const repoCache = [
  { name: 'flutter-pomodoro', description: 'Minimal pomodoro timer with adaptive Material 3 theming and focus statistics.',
    aiSummary: 'A small Flutter pomodoro timer. Adaptive Material 3 theming, weekly focus statistics, and a notification system that respects iOS focus modes.',
    techStack: ['Flutter', 'Dart', 'Material 3', 'Riverpod'], features: ['Adaptive Material 3 theming', 'Weekly focus charts', 'iOS focus-mode aware notifications', 'No tracking, no accounts'],
    languages: { Dart: 88, Swift: 7, Kotlin: 5 }, primary: 'Dart', stars: 184, forks: 12, pushedAt: '2026-04-28' },
  { name: 'spring-tasks', description: 'Self-hosted Kanban board with Spring Boot, PostgreSQL, and a Next.js client.',
    aiSummary: 'A self-hosted Kanban built in a weekend and slowly hardened over a semester. Spring Boot + JPA on the back, Next.js on the front, drag-and-drop reorder that holds up under flaky networks.',
    techStack: ['Java', 'Spring Boot', 'PostgreSQL', 'Next.js', 'TypeScript'], features: ['JWT auth + refresh-token rotation', 'Optimistic drag-and-drop reorder', 'PostgreSQL full-text search', 'Docker-compose dev environment'],
    languages: { Java: 62, TypeScript: 31, CSS: 7 }, primary: 'Java', stars: 96, forks: 8, pushedAt: '2026-03-12' },
  { name: 'pytorch-thai-handwriting', description: 'CNN classifier for Thai handwritten characters. 94.3% test accuracy on a 78-class set.',
    aiSummary: 'A small ResNet-style CNN trained on a hand-collected Thai character dataset. Includes the preprocessing scripts, training notebook, and a Flask demo. Reaches 94.3% test accuracy across 78 classes.',
    techStack: ['Python', 'PyTorch', 'NumPy', 'Flask'], features: ['Hand-collected 78-class dataset', '94.3% test accuracy', 'Augmentation pipeline with elastic transforms', 'Tiny Flask demo server'],
    languages: { Python: 95, HTML: 5 }, primary: 'Python', stars: 41, forks: 3, pushedAt: '2026-02-04' },
  { name: 'flutter-bus-tracker', description: 'Unofficial live tracker for the KMUTT shuttle bus, built for fellow students.',
    aiSummary: 'An unofficial live tracker for the KMUTT shuttle network. Scrapes the campus API, smooths positions with a Kalman filter, and pushes ETAs over a WebSocket to a Flutter client. Used by ~600 students daily.',
    techStack: ['Flutter', 'Dart', 'Go', 'WebSocket'], features: ['Kalman-filtered position smoothing', 'Offline-first cached schedules', '~600 daily active users', 'Self-hosted Go backend'],
    languages: { Dart: 78, Go: 18, Shell: 4 }, primary: 'Dart', stars: 312, forks: 24, pushedAt: '2026-04-09' },
  { name: 'react-native-receipts', description: 'Mobile receipt tracker for students. Camera OCR, monthly budget, expense rollups.',
    aiSummary: 'A receipt-tracking app I wrote because I kept losing my own. Uses on-device OCR via ML Kit, syncs to a tiny Node backend, and rolls up spending by category.',
    techStack: ['React Native', 'TypeScript', 'ML Kit', 'Node.js', 'SQLite'], features: ['On-device OCR via ML Kit', 'Offline-first SQLite store', 'Monthly budget rollups', 'Expo + EAS build pipeline'],
    languages: { TypeScript: 86, JavaScript: 9, Java: 5 }, primary: 'TypeScript', stars: 67, forks: 5, pushedAt: '2026-04-22' },
  { name: 'go-rss', description: 'Single-binary self-hosted RSS aggregator. SQLite, no JS, fast.',
    aiSummary: "A self-hosted RSS reader in a single Go binary. SQLite, server-rendered HTML, and a 200ms-end-to-end goal. I read every post I haven't deleted yet on it.",
    techStack: ['Go', 'SQLite', 'HTMX', 'Templ'], features: ['Single static binary', 'Sub-200ms page loads', 'OPML import/export', 'HTMX for partial updates'],
    languages: { Go: 81, HTML: 14, CSS: 5 }, primary: 'Go', stars: 218, forks: 16, pushedAt: '2026-03-30' },
  { name: 'kmutt-cs-notes', description: 'My CS notes from years 1–2 at KMUTT. Markdown, lots of diagrams.',
    aiSummary: 'My ongoing CS notebook from KMUTT — data structures, OOP, databases, discrete math. Written in Markdown, rendered to a static site, with hand-drawn diagrams.',
    techStack: ['Markdown', 'Astro', 'KaTeX'], features: ['Hand-drawn excalidraw diagrams', 'KaTeX math', 'Full-text search'],
    languages: { Markdown: 72, Astro: 18, CSS: 10 }, primary: 'Markdown', stars: 88, forks: 19, pushedAt: '2026-04-15' },
  { name: 'node-shorten', description: 'URL shortener I built before I learned Go. Express + SQLite.',
    aiSummary: 'A URL shortener built one weekend in my freshman year. Express + SQLite, base62 IDs, click tracking. Still running on a $4 VPS.',
    techStack: ['Node.js', 'Express', 'SQLite', 'TypeScript'], features: ['Base62 short IDs', 'Click counter + referer log', 'Tiny admin UI'],
    languages: { TypeScript: 88, EJS: 8, CSS: 4 }, primary: 'TypeScript', stars: 23, forks: 2, pushedAt: '2025-09-10' },
  { name: 'react-canvas-clock', description: 'Practice repo: hand-drawn analog clock with HTML canvas.',
    aiSummary: 'A practice project: an analog clock rendered to canvas, with configurable ticks, hands, and a quartz-inspired second hand that micro-jumps. Good for learning canvas math.',
    techStack: ['React', 'TypeScript', 'Canvas API'], features: ['Configurable faces', 'Micro-jumping second hand', '60fps via requestAnimationFrame'],
    languages: { TypeScript: 100 }, primary: 'TypeScript', stars: 14, forks: 1, pushedAt: '2025-11-20' },
  { name: 'next-portfolio', description: 'This very portfolio. Next.js, no analytics, no tracking.',
    aiSummary: 'This site. Next.js with static export, content driven by a config file, AI summaries cached so the homepage stays fast. Open-source, fork-friendly.',
    techStack: ['Next.js', 'TypeScript', 'Tailwind'], features: ['Static export', 'Config-driven content', 'No analytics, no tracking'],
    languages: { TypeScript: 92, CSS: 8 }, primary: 'TypeScript', stars: 9, forks: 0, pushedAt: '2026-05-08' },
];

// ─────────────────────────────────────────────────────────────────────────────
// LANG → swatch colour. Used for the language dot.
// ─────────────────────────────────────────────────────────────────────────────
const LANG_COLOURS = {
  TypeScript:'#3178C6', JavaScript:'#F1E05A', Dart:'#00B4AB', Python:'#3572A5',
  Go:'#00ADD8', Java:'#B07219', Rust:'#DEA584', CSS:'#563D7C', HTML:'#E34C26',
  Markdown:'#7A7264', Astro:'#FF5D01', Shell:'#89E051', Swift:'#F05138',
  Kotlin:'#A97BFF', EJS:'#A91E50',
};

// ─────────────────────────────────────────────────────────────────────────────
// helpers
// ─────────────────────────────────────────────────────────────────────────────
const NOW = new Date('2026-05-12');
const relTime = (iso) => {
  const d = (NOW - new Date(iso)) / 86400000;
  if (d < 2) return 'yesterday';
  if (d < 14) return `${Math.round(d)} days ago`;
  if (d < 60) return `${Math.round(d/7)} weeks ago`;
  if (d < 365) return `${Math.round(d/30)} months ago`;
  return `${Math.round(d/365)} year${Math.round(d/365) > 1 ? 's' : ''} ago`;
};
const langPct = (langs) => {
  const total = Object.values(langs).reduce((a,b)=>a+b,0) || 1;
  return Object.entries(langs).map(([n,v]) => ({ name:n, pct: Math.round(v/total*100) }));
};

// Aggregate skills across all repos
const techAggregate = (() => {
  const sum = {};
  repoCache.forEach(r => {
    Object.entries(r.languages).forEach(([n,v]) => { sum[n] = (sum[n] || 0) + v; });
  });
  const total = Object.values(sum).reduce((a,b)=>a+b,0) || 1;
  return Object.entries(sum).map(([n,v]) => ({ name:n, pct: +(v/total*100).toFixed(1) }))
    .sort((a,b) => b.pct - a.pct);
})();

// Pseudo-random deterministic contribution grid (53w × 7d)
const CONTRIB = (() => {
  const h = (i) => { const x = Math.sin(i * 1313.7) * 10000; return x - Math.floor(x); };
  const out = [];
  for (let w=0; w<53; w++) for (let d=0; d<7; d++) {
    const r = h(w*7 + d);
    const weekend = d === 0 || d === 6;
    const boost = (w > 6 && w < 18) || (w > 28 && w < 38) ? 0.3 : 0;
    const base = (weekend ? 0.2 : 0.5) + boost;
    const v = r < (1 - base) ? 0 : Math.min(4, Math.floor((r - (1-base)) * 9));
    out.push(v);
  }
  return out;
})();
const CONTRIB_TOTAL = CONTRIB.reduce((a,b)=>a+b,0) * 2; // visual fudge for "commits"
const CONTRIB_PALETTE = ['#EBE4D2', '#C7D7C5', '#7AA288', '#3A7A4D', '#1E4D2B'];

// ─────────────────────────────────────────────────────────────────────────────
// ICONS — inline SVG, inherit currentColor
// ─────────────────────────────────────────────────────────────────────────────
const Icon = {
  Star:    p => <svg viewBox="0 0 24 24" fill="currentColor" {...p}><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77 5.82 21l1.18-6.88L2 9.27l6.91-1.01L12 2z"/></svg>,
  StarOut: p => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" {...p}><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26"/></svg>,
  Fork:    p => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" {...p}><circle cx="6" cy="5" r="2"/><circle cx="6" cy="19" r="2"/><circle cx="18" cy="9" r="2"/><path d="M6 7v6a4 4 0 004 4h2"/><path d="M18 11v2a4 4 0 01-4 4h-2"/></svg>,
  GitHub:  p => <svg viewBox="0 0 24 24" fill="currentColor" {...p}><path d="M12 .5C5.7.5.5 5.7.5 12c0 5 3.3 9.3 7.8 10.8.6.1.8-.2.8-.6v-2.2c-3.2.7-3.9-1.4-3.9-1.4-.5-1.3-1.3-1.7-1.3-1.7-1.1-.7.1-.7.1-.7 1.2.1 1.8 1.2 1.8 1.2 1 1.8 2.7 1.3 3.4 1 .1-.8.4-1.3.7-1.6-2.6-.3-5.3-1.3-5.3-5.7 0-1.3.4-2.3 1.2-3.1-.1-.3-.5-1.5.1-3.1 0 0 1-.3 3.3 1.2 1-.3 2-.4 3-.4s2 .1 3 .4c2.3-1.6 3.3-1.2 3.3-1.2.6 1.6.2 2.8.1 3.1.8.8 1.2 1.9 1.2 3.1 0 4.4-2.7 5.4-5.3 5.7.4.3.8 1 .8 2v3c0 .3.2.7.8.6 4.5-1.5 7.8-5.8 7.8-10.8C23.5 5.7 18.3.5 12 .5z"/></svg>,
  LinkedIn: p => <svg viewBox="0 0 24 24" fill="currentColor" {...p}><path d="M19 3H5a2 2 0 00-2 2v14a2 2 0 002 2h14a2 2 0 002-2V5a2 2 0 00-2-2zM8.34 18.34H5.67V9.75h2.67v8.59zM7 8.58A1.55 1.55 0 1110 8.58a1.55 1.55 0 01-2.99 0zm11.34 9.76h-2.67v-4.66c0-1.11-.02-2.55-1.55-2.55s-1.79 1.21-1.79 2.47v4.74h-2.67V9.75h2.56v1.17h.04c.36-.67 1.22-1.38 2.52-1.38 2.7 0 3.2 1.78 3.2 4.09v4.71z"/></svg>,
  Mail:    p => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" {...p}><rect x="3" y="5" width="18" height="14" rx="1"/><path d="M3 7l9 6 9-6"/></svg>,
  Search:  p => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" {...p}><circle cx="11" cy="11" r="7"/><path d="M21 21l-4.3-4.3"/></svg>,
  X:       p => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" {...p}><path d="M18 6L6 18M6 6l12 12"/></svg>,
  ArrowUR: p => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" {...p}><path d="M7 17L17 7M8 7h9v9"/></svg>,
  Download:p => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" {...p}><path d="M12 3v12m0 0l-4-4m4 4l4-4M4 21h16"/></svg>,
  MapPin:  p => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" {...p}><path d="M12 22s7-7.5 7-13a7 7 0 10-14 0c0 5.5 7 13 7 13z"/><circle cx="12" cy="9" r="2.5"/></svg>,
  Sparkle: p => <svg viewBox="0 0 24 24" fill="currentColor" {...p}><path d="M12 2.5L13.6 9 20 10.5 13.6 12 12 18.5 10.4 12 4 10.5 10.4 9z"/></svg>,
};

// ─────────────────────────────────────────────────────────────────────────────
// SHARED PRIMITIVES + animation helpers
// ─────────────────────────────────────────────────────────────────────────────
const Kicker = ({children, className=''}) => (
  <div className={`font-mono text-[11px] uppercase tracking-[0.18em] text-ink-3 whitespace-nowrap ${className}`}>{children}</div>
);
const Rule = ({className=''}) => <div className={'h-px bg-rule ' + className}/>;
const SectionHead = ({num, title, sub}) => (
  <div className="mb-8">
    <Kicker>§ {num} {sub && <>· {sub}</>}</Kicker>
    <h2 className="font-serif text-[36px] md:text-[44px] leading-[1.0] tracking-[-0.02em] text-ink mt-2">{title}</h2>
  </div>
);

// Count up from 0 to `to` over `ms`, easing out. Returns current integer value.
function useCountUp(to, ms = 1200, deps = []) {
  const [v, setV] = React.useState(0);
  React.useEffect(() => {
    let raf, start;
    const tick = (t) => {
      if (!start) start = t;
      const p = Math.min(1, (t - start) / ms);
      const eased = 1 - Math.pow(1 - p, 3); // easeOutCubic
      setV(Math.round(to * eased));
      if (p < 1) raf = requestAnimationFrame(tick);
    };
    raf = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(raf);
    // eslint-disable-next-line
  }, deps);
  return v;
}

// Decorative stamp/seal — rotated badge for the hero info card
function Stamp({children, rotate=-4}) {
  return (
    <div className="inline-flex items-center gap-1.5 px-2 py-1 border-2 border-forest text-forest font-mono text-[10px] uppercase tracking-[0.18em] whitespace-nowrap"
         style={{transform: `rotate(${rotate}deg)`}}>
      <span className="relative flex h-1.5 w-1.5">
        <span className="absolute inline-flex h-full w-full rounded-full bg-forest opacity-50 pulse-dot"/>
        <span className="relative inline-flex rounded-full h-1.5 w-1.5 bg-forest"/>
      </span>
      {children}
    </div>
  );
}

// Circular avatar with initials + animated stroke
function Avatar({initials = 'PB', size = 72}) {
  return (
    <div className="relative inline-block" style={{width: size, height: size}}>
      <svg viewBox="0 0 80 80" width={size} height={size} className="absolute inset-0">
        <circle cx="40" cy="40" r="38" fill="none" stroke="currentColor" strokeWidth="1.5"
                className="text-ink/15" />
        <circle cx="40" cy="40" r="38" fill="none" stroke="#1E4D2B" strokeWidth="1.5"
                strokeDasharray="239" strokeDashoffset="239" pathLength="239"
                style={{animation: 'avatarStroke 1.4s cubic-bezier(0.2, 0.8, 0.2, 1) 0.4s forwards', transform: 'rotate(-90deg)', transformOrigin: 'center'}}/>
      </svg>
      <div className="absolute inset-0 flex items-center justify-center font-serif text-[28px] text-ink tracking-[-0.02em] leading-none">
        {initials}
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// REPO CARD — the most important unit
// ─────────────────────────────────────────────────────────────────────────────
function RepoCard({ repo, index, onClick, featured, animateDelay }) {
  const langColour = LANG_COLOURS[repo.primary] || '#7A7264';
  const pct = langPct(repo.languages);
  // active = pushed within last 14 days
  const daysSince = (NOW - new Date(repo.pushedAt)) / 86400000;
  const active = daysSince < 30;
  return (
    <article onClick={onClick}
      style={animateDelay != null ? {animationDelay: animateDelay + 'ms'} : undefined}
      className={`repo-card group relative bg-paper-2 border border-rule hover:border-ink transition-colors duration-150 cursor-pointer flex flex-col ${animateDelay != null ? 'fade-up' : ''} ${featured ? 'md:col-span-2 md:row-span-1' : ''}`}>
      {/* index strip */}
      <div className="flex items-center justify-between px-4 py-2 border-b border-rule bg-paper-3/30">
        <div className="font-mono text-[10.5px] uppercase tracking-[0.16em] text-ink-3 whitespace-nowrap flex items-center gap-2">
          № {String(index).padStart(3,'0')} · {repo.primary}
          {featured && <span className="inline-flex items-center gap-1 px-1.5 py-px bg-forest text-paper rounded-[1px] tracking-[0.14em]">★ FEATURED</span>}
          {active && !featured && (
            <span className="inline-flex items-center gap-1 px-1.5 py-px border border-forest text-forest rounded-[1px] tracking-[0.14em]">
              <span className="relative inline-flex h-1 w-1 rounded-full bg-forest wip-pulse"/> WIP
            </span>
          )}
        </div>
        <div className="font-mono text-[10.5px] tnum text-ink-3 flex items-center gap-1">
          <Icon.Star className="w-2.5 h-2.5 text-forest" /> {repo.stars}
        </div>
      </div>
      {/* body */}
      <div className="p-5 flex-1 flex flex-col">
        <h3 className={`font-serif ${featured ? 'text-[34px] md:text-[38px]' : 'text-[26px]'} leading-[1.05] text-ink tracking-[-0.01em] mb-3`}>
          {repo.name.split('-').map((p, i, arr) => (
            <React.Fragment key={i}>
              {i === arr.length - 1 && arr.length > 1
                ? <em className="italic text-forest">{p}</em>
                : p}
              {i < arr.length - 1 && <span className="text-ink-4">-</span>}
            </React.Fragment>
          ))}
        </h3>
        <p className={`font-serif ${featured ? 'text-[17px] md:text-[18px] max-w-[640px]' : 'text-[15px]'} leading-[1.5] text-ink-2 mb-4 flex-1`}>{repo.aiSummary}</p>
        {/* topics */}
        <div className="flex flex-wrap gap-1.5 mb-4">
          {repo.techStack.slice(0, featured ? 6 : 4).map(t => (
            <span key={t} className="px-2 py-0.5 font-mono text-[10.5px] tracking-[0.04em] text-ink-2 border border-rule bg-paper rounded-[1px]">{t}</span>
          ))}
        </div>
      </div>
      {/* footer */}
      <div className="flex items-center justify-between px-4 py-2.5 border-t border-rule font-mono text-[10.5px] text-ink-3">
        <div className="flex items-center gap-2">
          <span className="inline-block w-2 h-2 rounded-full" style={{background: langColour}}/>
          {repo.primary} <span className="text-ink-4">· {pct[0]?.pct}%</span>
        </div>
        <div className="flex items-center gap-2 tnum">
          <span>updated {relTime(repo.pushedAt)}</span>
          <span className="arrow-affordance text-forest"><Icon.ArrowUR className="w-3 h-3"/></span>
        </div>
      </div>
    </article>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// REPO MODAL — opens on card click
// ─────────────────────────────────────────────────────────────────────────────
function RepoModal({ repo, onClose }) {
  React.useEffect(() => {
    if (!repo) return;
    const k = (e) => e.key === 'Escape' && onClose();
    window.addEventListener('keydown', k);
    document.body.style.overflow = 'hidden';
    return () => { window.removeEventListener('keydown', k); document.body.style.overflow = ''; };
  }, [repo, onClose]);
  if (!repo) return null;
  const pct = langPct(repo.languages);
  return (
    <div onClick={onClose} className="fixed inset-0 z-40 bg-ink/40 flex items-start md:items-center justify-center p-3 md:p-8 overflow-y-auto scale-in">
      <div onClick={(e)=>e.stopPropagation()} className="relative w-full max-w-[820px] bg-paper border border-ink shadow-[0_1px_0_rgba(0,0,0,0.04)] my-auto">
        {/* close */}
        <button onClick={onClose} aria-label="Close" className="absolute top-3 right-3 w-9 h-9 flex items-center justify-center text-ink-3 hover:text-ink hover:bg-paper-3">
          <Icon.X className="w-4 h-4"/>
        </button>
        {/* header */}
        <div className="px-7 pt-7 pb-5 border-b border-rule">
          <Kicker>Repository · {repo.primary} · ★ {repo.stars}</Kicker>
          <h2 className="font-serif text-[44px] leading-[1.0] tracking-[-0.015em] text-ink mt-2">
            {repo.name.split('-').map((p, i, arr) => (
              <React.Fragment key={i}>
                {i === arr.length - 1 && arr.length > 1
                  ? <em className="italic text-forest">{p}</em>
                  : p}
                {i < arr.length - 1 && <span className="text-ink-4">-</span>}
              </React.Fragment>
            ))}
          </h2>
          <p className="font-serif text-[18px] leading-[1.5] text-ink-2 mt-3 max-w-[640px]">{repo.aiSummary}</p>
        </div>
        {/* body grid */}
        <div className="grid grid-cols-1 md:grid-cols-3">
          <div className="md:col-span-2 px-7 py-6 border-r border-rule">
            <Kicker>What's in it</Kicker>
            <ul className="mt-3 space-y-2.5">
              {repo.features.map(f => (
                <li key={f} className="font-serif text-[15px] leading-[1.5] text-ink flex items-start gap-3">
                  <span className="mt-2 inline-block w-1.5 h-1.5 bg-forest rounded-full shrink-0"/>{f}
                </li>
              ))}
            </ul>
            <div className="mt-7">
              <Kicker>README preview</Kicker>
              <div className="mt-3 bg-paper-3/40 border border-rule p-4 font-mono text-[12px] leading-[1.7] text-ink-2">
                <div className="text-ink font-medium"># {repo.name}</div>
                <div>{repo.description}</div>
                <div className="mt-2 text-ink-3">## Install</div>
                <div>$ git clone {config.user.githubUrl}/{repo.name}</div>
                <div>$ cd {repo.name} &amp;&amp; make</div>
                <div className="mt-2 text-ink-3">## Stack</div>
                <div>— {repo.techStack.join(' · ')}</div>
              </div>
            </div>
          </div>
          <div className="px-7 py-6">
            <Kicker>Tech stack</Kicker>
            <div className="mt-3 flex flex-wrap gap-1.5">
              {repo.techStack.map(t => (
                <span key={t} className="px-2 py-1 font-mono text-[11px] text-ink-2 border border-rule bg-paper-2">{t}</span>
              ))}
            </div>
            <div className="mt-6">
              <Kicker>Languages</Kicker>
              <div className="mt-3 flex h-2 overflow-hidden border border-rule">
                {pct.map(p => <div key={p.name} style={{width: p.pct+'%', background: LANG_COLOURS[p.name] || '#7A7264'}}/>)}
              </div>
              <div className="mt-2 space-y-1">
                {pct.map(p => (
                  <div key={p.name} className="flex items-center justify-between font-mono text-[11px]">
                    <span className="flex items-center gap-1.5"><span className="w-2 h-2 rounded-full" style={{background: LANG_COLOURS[p.name] || '#7A7264'}}/> {p.name}</span>
                    <span className="text-ink-3 tnum">{p.pct}%</span>
                  </div>
                ))}
              </div>
            </div>
            <div className="mt-6">
              <Kicker>Meta</Kicker>
              <dl className="mt-3 font-mono text-[11.5px] space-y-1">
                <div className="flex justify-between"><dt className="text-ink-3">Stars</dt><dd className="text-ink tnum">{repo.stars}</dd></div>
                <div className="flex justify-between"><dt className="text-ink-3">Forks</dt><dd className="text-ink tnum">{repo.forks}</dd></div>
                <div className="flex justify-between"><dt className="text-ink-3">Updated</dt><dd className="text-ink">{relTime(repo.pushedAt)}</dd></div>
              </dl>
            </div>
            <a href={config.user.githubUrl + '/' + repo.name} target="_blank" rel="noreferrer"
               className="mt-6 inline-flex items-center justify-center gap-2 w-full px-3 py-2.5 bg-ink text-paper hover:bg-forest font-mono text-[12px] uppercase tracking-[0.14em] transition-colors">
              <Icon.GitHub className="w-3.5 h-3.5"/> View on GitHub <Icon.ArrowUR className="w-3 h-3"/>
            </a>
          </div>
        </div>
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// HEADER + FOOTER
// ─────────────────────────────────────────────────────────────────────────────
function Header({page, setPage, theme, setTheme}) {
  return (
    <header className="sticky top-0 z-30 bg-paper/85 backdrop-blur-sm border-b border-rule">
      <div className="max-w-[1100px] mx-auto px-6 h-14 flex items-center justify-between gap-4">
        <button onClick={() => setPage('home')} className="flex items-baseline gap-1 group">
          <span className="font-serif text-[20px] text-ink leading-none">Punnatorn</span>
          <span className="font-mono text-[10.5px] uppercase tracking-[0.18em] text-ink-3 group-hover:text-forest transition-colors">— {config.user.handle}</span>
        </button>
        <nav className="flex items-center gap-1">
          {['home', 'projects', 'about'].map(p => (
            <button key={p} onClick={() => setPage(p)}
              className={`px-3 py-1.5 font-mono text-[11.5px] uppercase tracking-[0.14em] transition-colors ${page === p ? 'text-ink underline-forest' : 'text-ink-3 hover:text-ink'}`}>
              {p}
            </button>
          ))}
          <ThemeSwitcher theme={theme} setTheme={setTheme}/>
          <a href="#cv" onClick={(e)=>e.preventDefault()} className="ml-1 inline-flex items-center gap-1.5 px-3 py-1.5 bg-ink text-paper hover:bg-forest font-mono text-[11.5px] uppercase tracking-[0.14em] transition-colors">
            <Icon.Download className="w-3 h-3"/> CV
          </a>
        </nav>
      </div>
    </header>
  );
}

function ThemeSwitcher({theme, setTheme}) {
  const themes = [
    { id: 'sans',  label: 'Sans',  hint: 'Modern grotesk' },
    { id: 'mono',  label: 'Mono',  hint: 'Developer brutalist' },
    { id: 'serif', label: 'Serif', hint: 'Editorial classic' },
  ];
  return (
    <div className="ml-2 mr-1 flex items-center gap-0 border border-rule bg-paper-2">
      {themes.map(tt => (
        <button key={tt.id} onClick={() => setTheme(tt.id)} title={tt.hint}
          className={`px-2 py-1 font-mono text-[10.5px] uppercase tracking-[0.12em] transition-colors ${theme === tt.id ? 'bg-ink text-paper' : 'text-ink-3 hover:text-ink'}`}>
          {tt.label}
        </button>
      ))}
    </div>
  );
}
function Footer() {
  return (
    <footer className="border-t border-rule bg-paper-2">
      <div className="max-w-[1100px] mx-auto px-6 py-8 flex flex-wrap items-center justify-between gap-3 font-mono text-[11.5px] text-ink-3">
        <span>© 2026 {config.user.name} · Made in Bangkok</span>
        <span className="flex items-center gap-1.5">
          <span className="relative flex h-1.5 w-1.5">
            <span className="absolute inline-flex h-full w-full rounded-full bg-forest opacity-50 pulse-dot"/>
            <span className="relative inline-flex rounded-full h-1.5 w-1.5 bg-forest"/>
          </span>
          Synced with GitHub · today
        </span>
      </div>
    </footer>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// HOME
// ─────────────────────────────────────────────────────────────────────────────
function ContributionGraph() {
  const total = useCountUp(CONTRIB_TOTAL, 1500);
  return (
    <div className="bg-paper-2 border border-rule p-5">
      <div className="flex items-baseline justify-between mb-4 gap-3 flex-wrap">
        <div>
          <Kicker>Activity · last 12 months</Kicker>
          <div className="font-serif text-[28px] text-ink leading-none tnum mt-1">
            {total.toLocaleString()} <span className="text-ink-3 text-[14px]">contributions</span>
          </div>
        </div>
        <div className="font-mono text-[10.5px] uppercase tracking-[0.14em] text-ink-3 flex items-center gap-1.5">
          Less {CONTRIB_PALETTE.map((c, i) => (
            <span key={i} className="inline-block w-2.5 h-2.5 rounded-[1px]" style={{background: c, border: i === 0 ? '1px solid #D9D1BC' : 'none'}}/>
          ))} More
        </div>
      </div>
      <div className="overflow-x-auto" style={{scrollbarWidth: 'none'}}>
        <div className="flex gap-[3px] min-w-[720px]">
          {Array.from({length: 53}).map((_, w) => (
            <div key={w} className="flex flex-col gap-[3px]">
              {Array.from({length: 7}).map((_, d) => {
                const v = CONTRIB[w*7 + d];
                return <div key={d} className="w-[11px] h-[11px] rounded-[1px] contrib-pop"
                  style={{
                    background: CONTRIB_PALETTE[v],
                    border: v === 0 ? '1px solid #D9D1BC' : 'none',
                    animationDelay: (w * 14 + d * 6) + 'ms',
                  }}/>;
              })}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
function TechStackBar() {
  return (
    <div className="bg-paper-2 border border-rule p-5">
      <div className="flex items-baseline justify-between mb-4">
        <Kicker>Aggregated tech stack</Kicker>
        <span className="font-mono text-[10.5px] text-ink-3 tnum whitespace-nowrap">{techAggregate.length} languages · {repoCache.length} repos</span>
      </div>
      <div className="w-full h-3 flex overflow-hidden border border-rule mb-4">
        {techAggregate.map(s => (
          <div key={s.name} title={`${s.name} ${s.pct}%`} style={{width: s.pct+'%', background: LANG_COLOURS[s.name] || '#7A7264'}}/>
        ))}
      </div>
      <div className="flex flex-wrap gap-x-5 gap-y-2">
        {techAggregate.map(s => (
          <div key={s.name} className="flex items-center gap-1.5 font-mono text-[12px]">
            <span className="inline-block w-2.5 h-2.5 rounded-full" style={{background: LANG_COLOURS[s.name] || '#7A7264'}}/>
            <span className="text-ink">{s.name}</span>
            <span className="text-ink-4 tnum">{s.pct}%</span>
          </div>
        ))}
      </div>
    </div>
  );
}
function Home({setPage, openRepo}) {
  const pinned = config.pinnedRepos.map(slug => repoCache.find(r => r.name === slug)).filter(Boolean);
  const totalStars = repoCache.reduce((a, r) => a + r.stars, 0);
  const animStars  = useCountUp(totalStars, 1400);
  const animRepos  = useCountUp(repoCache.length, 900);
  const animLangs  = useCountUp(techAggregate.length, 900);

  return (
    <div>
      {/* HERO */}
      <section className="max-w-[1100px] mx-auto px-6 pt-16 pb-14">
        <div className="grid grid-cols-1 md:grid-cols-12 gap-10">
          <div className="md:col-span-8">
            <h1 className="font-serif text-[clamp(48px,7.4vw,96px)] leading-[0.92] tracking-[-0.025em] text-ink">
              <span className="block fade-up d-0">{config.user.given}</span>
              <span className="block fade-up d-1 surname-hover"><em className="italic text-forest">{config.user.surname}.</em></span>
            </h1>
            <p className="font-serif text-[20px] md:text-[22px] leading-[1.5] text-ink-2 mt-7 max-w-[640px] fade-up d-2">
              {config.user.bio}
            </p>
          </div>
          {/* card */}
          <div className="md:col-span-4 md:pt-3 slide-in-right d-2">
            <div className="border-t-2 border-ink pt-6 space-y-6 relative">
              <div className="fade-up d-3">
                <Kicker>Find</Kicker>
                <ul className="mt-2 font-mono text-[12.5px] text-ink space-y-1">
                  <li className="flex items-center gap-2"><Icon.GitHub className="w-3.5 h-3.5"/> <a className="hover:text-forest" href={config.user.githubUrl}>{config.user.github}</a></li>
                  <li className="flex items-center gap-2"><Icon.LinkedIn className="w-3.5 h-3.5"/> <a className="hover:text-forest">{config.user.linkedin}</a></li>
                  <li className="flex items-center gap-2"><Icon.Mail className="w-3.5 h-3.5"/> <a className="hover:text-forest" href={'mailto:' + config.user.email}>{config.user.email}</a></li>
                </ul>
              </div>

              <div className="flex flex-wrap gap-2 pt-1 fade-up d-6">
                <a href="#cv" onClick={(e)=>e.preventDefault()} className="inline-flex items-center gap-2 px-3 py-2 bg-ink text-paper hover:bg-forest font-mono text-[11.5px] uppercase tracking-[0.14em] transition-colors">
                  <Icon.Download className="w-3.5 h-3.5"/> CV
                </a>
                <a href={'mailto:' + config.user.email} className="inline-flex items-center gap-2 px-3 py-2 border border-ink text-ink hover:bg-ink hover:text-paper font-mono text-[11.5px] uppercase tracking-[0.14em] transition-colors">
                  <Icon.Mail className="w-3.5 h-3.5"/> Email
                </a>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* PINNED */}
      <section className="max-w-[1100px] mx-auto px-6 pb-12">
        <div className="flex items-end justify-between mb-10 gap-3 flex-wrap">
          <div>
            <Kicker>§ 02 · Pinned · {pinned.length}</Kicker>
            <h2 className="font-serif text-[40px] md:text-[48px] leading-[1.0] tracking-[-0.02em] text-ink mt-2">The <em className="italic text-forest">good</em> stuff.</h2>
          </div>
          <button onClick={() => setPage('projects')} className="font-mono text-[11.5px] uppercase tracking-[0.14em] text-ink-2 hover:text-forest flex items-center gap-1.5">
            All {repoCache.length} repositories <Icon.ArrowUR className="w-3 h-3"/>
          </button>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
          {pinned.map((r, i) => (
            <RepoCard key={r.name} repo={r} index={repoCache.findIndex(x => x.name === r.name) + 1}
                      featured={i === 0} animateDelay={i * 90}
                      onClick={() => openRepo(r)}/>
          ))}
        </div>
      </section>

      {/* STATS BAND */}
      <section className="max-w-[1100px] mx-auto px-6 pb-12">
        <div className="mb-10">
          <Kicker>§ 03 · Numerics</Kicker>
          <h2 className="font-serif text-[40px] md:text-[48px] leading-[1.0] tracking-[-0.02em] text-ink mt-2">By the <em className="italic text-forest">numbers</em>.</h2>
        </div>

        {/* stat tiles */}
        <div className="grid grid-cols-3 gap-px bg-rule border border-rule mb-5">
          {[
            {label: 'Repositories', value: animRepos, suffix: ''},
            {label: 'Stars earned', value: animStars,  suffix: ''},
            {label: 'Languages',    value: animLangs,  suffix: ''},
          ].map(s => (
            <div key={s.label} className="bg-paper-2 p-5">
              <Kicker>{s.label}</Kicker>
              <div className="font-serif text-[clamp(36px,5vw,56px)] leading-[1.0] tracking-[-0.02em] text-ink tnum mt-2">
                {s.value.toLocaleString()}{s.suffix}
              </div>
            </div>
          ))}
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
          <TechStackBar/>
          <ContributionGraph/>
        </div>
      </section>
      <Footer/>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// PROJECTS — filter / sort / search
// ─────────────────────────────────────────────────────────────────────────────
function Projects({openRepo}) {
  const [q, setQ] = React.useState('');
  const [lang, setLang] = React.useState('All');
  const [sort, setSort] = React.useState('stars');
  const [loading, setLoading] = React.useState(true);
  React.useEffect(() => { const t = setTimeout(() => setLoading(false), 700); return () => clearTimeout(t); }, []);

  const langs = ['All', ...Array.from(new Set(repoCache.map(r => r.primary)))];
  const filtered = React.useMemo(() => {
    let out = [...repoCache];
    if (q.trim()) {
      const s = q.toLowerCase();
      out = out.filter(r => r.name.toLowerCase().includes(s) || r.aiSummary.toLowerCase().includes(s) || r.techStack.some(t => t.toLowerCase().includes(s)));
    }
    if (lang !== 'All') out = out.filter(r => r.primary === lang);
    out.sort((a,b) =>
      sort === 'stars'   ? b.stars - a.stars :
      sort === 'updated' ? new Date(b.pushedAt) - new Date(a.pushedAt) :
      sort === 'created' ? a.name.localeCompare(b.name) :
                            a.name.localeCompare(b.name)
    );
    return out;
  }, [q, lang, sort]);

  return (
    <div>
      <section className="max-w-[1100px] mx-auto px-6 pt-14 pb-8">
        <Kicker className="fade-up d-0">§ 01 · All work, all repositories</Kicker>
        <h1 className="font-serif text-[clamp(48px,7vw,88px)] leading-[0.95] tracking-[-0.02em] text-ink mt-3 fade-up d-1">The <em className="italic text-forest">complete</em> catalogue.</h1>
        <p className="font-serif text-[18px] leading-[1.5] text-ink-2 mt-5 max-w-[640px] fade-up d-2">
          Every repository on my GitHub, summarised by an AI that reads the README so you don't have to. {repoCache.length} repos · {techAggregate.length} languages.
        </p>
      </section>

      {/* controls */}
      <section className="max-w-[1100px] mx-auto px-6 pb-6">
        <div className="bg-paper-2 border border-rule p-3 flex flex-wrap items-center gap-2">
          <div className="flex items-center gap-2 px-3 py-2 bg-paper border border-rule flex-1 min-w-[200px]">
            <Icon.Search className="w-3.5 h-3.5 text-ink-3"/>
            <input value={q} onChange={(e)=>setQ(e.target.value)} placeholder="search repos, tech, summaries…"
              className="bg-transparent outline-none w-full font-mono text-[13px] text-ink placeholder:text-ink-4"/>
            {q && <button onClick={() => setQ('')} className="text-ink-3 hover:text-ink"><Icon.X className="w-3 h-3"/></button>}
          </div>
          <div className="flex items-center gap-1 flex-wrap">
            {langs.map(l => (
              <button key={l} onClick={() => setLang(l)}
                className={`px-2.5 py-1.5 font-mono text-[11px] uppercase tracking-[0.08em] transition-colors ${lang === l ? 'bg-ink text-paper border border-ink' : 'border border-rule text-ink-2 hover:border-ink'}`}>
                {l}
              </button>
            ))}
          </div>
          <div className="flex items-center gap-2 px-3 py-1.5 bg-paper border border-rule">
            <span className="font-mono text-[10.5px] uppercase tracking-[0.14em] text-ink-3">Sort</span>
            <select value={sort} onChange={(e) => setSort(e.target.value)} className="bg-transparent font-mono text-[12px] outline-none text-ink">
              <option value="stars">Most stars</option>
              <option value="updated">Recently updated</option>
              <option value="created">Name (A–Z)</option>
            </select>
          </div>
        </div>
      </section>

      {/* grid */}
      <section className="max-w-[1100px] mx-auto px-6 pb-20">
        {loading ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
            {Array.from({length: 6}).map((_, i) => (
              <div key={i} className="bg-paper-2 border border-rule h-[320px]">
                <div className="h-9 border-b border-rule shimmer"/>
                <div className="p-5 space-y-3">
                  <div className="h-7 w-3/4 shimmer rounded-[1px]"/>
                  <div className="h-3 w-full shimmer rounded-[1px]"/>
                  <div className="h-3 w-5/6 shimmer rounded-[1px]"/>
                  <div className="flex gap-1.5 pt-2">
                    <div className="h-5 w-14 shimmer rounded-[1px]"/>
                    <div className="h-5 w-16 shimmer rounded-[1px]"/>
                    <div className="h-5 w-12 shimmer rounded-[1px]"/>
                  </div>
                </div>
              </div>
            ))}
          </div>
        ) : filtered.length === 0 ? (
          <div className="bg-paper-2 border border-rule p-12 text-center">
            <div className="font-serif text-[32px] italic text-forest mb-2">Nothing here yet.</div>
            <p className="font-serif text-[15px] text-ink-2 max-w-[400px] mx-auto leading-[1.5]">
              No repositories match. Try a softer search — or clear the filters and browse the full catalogue.
            </p>
            <button onClick={() => { setQ(''); setLang('All'); }} className="mt-5 px-4 py-2 border border-ink text-ink hover:bg-ink hover:text-paper font-mono text-[11.5px] uppercase tracking-[0.14em] transition-colors">
              Clear filters
            </button>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
            {filtered.map((r, i) => <RepoCard key={r.name} repo={r} index={repoCache.findIndex(x => x.name === r.name) + 1} animateDelay={i * 60} onClick={() => openRepo(r)}/>)}
          </div>
        )}
      </section>
      <Footer/>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// ABOUT
// ─────────────────────────────────────────────────────────────────────────────
function About() {
  return (
    <div>
      <section className="max-w-[860px] mx-auto px-6 pt-14 pb-12">
        <Kicker className="fade-up d-0">§ 01 · About — {config.user.nickname}</Kicker>
        <h1 className="font-serif text-[clamp(48px,7vw,88px)] leading-[0.95] tracking-[-0.02em] text-ink mt-3 fade-up d-1">
          Hello — I'm <em className="italic text-forest">{config.user.nickname}.</em>
        </h1>
        <p className="font-serif text-[19px] leading-[1.6] text-ink-2 mt-6 max-w-[640px] fade-up d-2">{config.user.bio}</p>
        <p className="font-serif text-[18px] leading-[1.65] text-ink mt-5 max-w-[640px] fade-up d-3">{config.user.aboutLong}</p>
      </section>

      <section className="max-w-[860px] mx-auto px-6 pb-12">
        <SectionHead num="02" title="Education"/>
        <div className="space-y-px">
          {config.education.map((e, i) => (
            <div key={i} className="bg-paper-2 border border-rule p-5 fade-up" style={{animationDelay: i * 80 + 'ms'}}>
              <div className="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-1">
                <h3 className="font-serif text-[22px] leading-[1.2] text-ink">{e.school}</h3>
                <div className="font-mono text-[11px] uppercase tracking-[0.14em] text-ink-3 whitespace-nowrap">{e.years}</div>
              </div>
              <div className="font-serif italic text-[15px] text-forest mt-1">{e.degree}</div>
              <div className="font-mono text-[12px] text-ink-2 mt-2 leading-[1.6]">{e.detail}</div>
            </div>
          ))}
        </div>
      </section>

      <section className="max-w-[860px] mx-auto px-6 pb-12">
        <SectionHead num="03" title="Activities"/>
        <div className="relative pl-5">
          {/* vertical timeline rule */}
          <div className="absolute left-1.5 top-1.5 bottom-1.5 w-px bg-rule"/>
          <ul className="space-y-5">
            {config.user.activities.map((a, i) => (
              <li key={a.title} className="relative fade-up" style={{animationDelay: i * 80 + 'ms'}}>
                <span className="absolute -left-[18px] top-2 w-2.5 h-2.5 rounded-full bg-forest ring-4 ring-paper"/>
                <div className="flex flex-wrap items-baseline justify-between gap-x-4">
                  <h3 className="font-serif text-[19px] leading-[1.2] text-ink">{a.title}</h3>
                  <div className="font-mono text-[11px] uppercase tracking-[0.14em] text-ink-3 tnum whitespace-nowrap">{a.year}</div>
                </div>
                <p className="font-mono text-[12px] text-ink-2 leading-[1.6] mt-1">{a.detail}</p>
              </li>
            ))}
          </ul>
        </div>
      </section>

      <section className="max-w-[860px] mx-auto px-6 pb-12">
        <SectionHead num="04" title="Languages"/>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-px bg-rule border border-rule">
          {config.user.spokenLanguages.map((l, i) => (
            <div key={l.name} className="bg-paper-2 p-5 fade-up" style={{animationDelay: i * 80 + 'ms'}}>
              <Kicker>{l.level}</Kicker>
              <div className="font-serif text-[28px] leading-[1.0] tracking-[-0.01em] text-ink mt-2">{l.name}</div>
            </div>
          ))}
        </div>
      </section>

      <section className="max-w-[860px] mx-auto px-6 pb-12">
        <SectionHead num="05" title="Skills"/>
        <div className="bg-paper-2 border border-rule divide-y divide-rule">
          {Object.entries(config.skills).map(([cat, items]) => (
            <div key={cat} className="grid grid-cols-1 md:grid-cols-4 gap-3 p-5">
              <div className="md:col-span-1"><Kicker>{cat}</Kicker></div>
              <div className="md:col-span-3 flex flex-wrap gap-1.5">
                {items.map(s => (
                  <span key={s} className="px-2 py-0.5 font-mono text-[11.5px] text-ink border border-rule bg-paper">{s}</span>
                ))}
              </div>
            </div>
          ))}
        </div>
      </section>

      <section className="max-w-[860px] mx-auto px-6 pb-20">
        <SectionHead num="06" title="Get in touch"/>
        <div className="bg-paper-2 border border-rule p-6 flex flex-wrap items-center justify-between gap-4">
          <div>
            <p className="font-serif text-[18px] text-ink max-w-[440px] leading-[1.5]">
              I'm <em className="italic text-forest">open</em> for {config.user.season} internships and reading interesting cold emails.
            </p>
          </div>
          <div className="flex flex-wrap gap-2">
            <a href={'mailto:' + config.user.email} className="inline-flex items-center gap-2 px-4 py-2.5 bg-ink text-paper hover:bg-forest font-mono text-[12px] uppercase tracking-[0.14em] transition-colors">
              <Icon.Mail className="w-3.5 h-3.5"/> Email
            </a>
            <a href={config.user.githubUrl} className="inline-flex items-center gap-2 px-4 py-2.5 border border-ink text-ink hover:bg-ink hover:text-paper font-mono text-[12px] uppercase tracking-[0.14em] transition-colors">
              <Icon.GitHub className="w-3.5 h-3.5"/> GitHub
            </a>
            <a href="#cv" onClick={(e)=>e.preventDefault()} className="inline-flex items-center gap-2 px-4 py-2.5 border border-ink text-ink hover:bg-ink hover:text-paper font-mono text-[12px] uppercase tracking-[0.14em] transition-colors">
              <Icon.Download className="w-3.5 h-3.5"/> Download CV
            </a>
          </div>
        </div>
      </section>
      <Footer/>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// APP
// ─────────────────────────────────────────────────────────────────────────────
function App() {
  const [page, setPage] = React.useState('home');
  const [theme, setTheme] = React.useState('sans');
  const [openRepoData, setOpenRepoData] = React.useState(null);
  return (
    <div className="min-h-screen bg-paper" data-theme={theme}>
      <Header page={page} setPage={(p)=>{ setPage(p); window.scrollTo(0,0); }} theme={theme} setTheme={setTheme}/>
      <div key={page} className="fade-up">
        {page === 'home'     && <Home setPage={setPage} openRepo={setOpenRepoData}/>}
        {page === 'projects' && <Projects openRepo={setOpenRepoData}/>}
        {page === 'about'    && <About/>}
      </div>
      <RepoModal repo={openRepoData} onClose={() => setOpenRepoData(null)}/>
    </div>
  );
}
ReactDOM.createRoot(document.getElementById('root')).render(<App/>);
